### ISSUE TITLE
ImportError: cannot import name 'AutoModel' from 'transformers' (unknown location)

### ISSUE THREAD

**Issue by zy614582280** [HIT-SCIR/ltp#535]
pip install ltp==4.1.5.post2
win10 引用ltp 报错
![image](https://user-images.githubusercontent.com/23072890/129569219-7766dd0f-b990-4b8c-b7e5-caac255f5489.png)

**Comment by zy614582280** [comment]
破案了，这个问题是torch的版本过低导致。
transformers 需要torch >= 1.3.0。

**Comment by zy614582280** [comment]
![image](https://user-images.githubusercontent.com/23072890/129655751-2beea020-bf43-4ba6-91a9-4a6032541956.png)

**Comment by Reagan1947** [comment]
> Issue link： https://github.com/huggingface/transformers/issues/4172
> Reference this issue 参考上述链接的[Issue #4172](https://github.com/huggingface/transformers/issues/4172)
> ImportError: cannot import name 'AutoModel' from 'transformers' #4172


## 1. Install Tensorflow or Torch 安装TF或Torch
AutoModel is the equivalent of TFAutoModel but for PyTorch model classes. If you don't have pytorch installed this is expected.

AutoModel相当于TFAutoModel，但用于PyTorch模型类。如果你没有安装pytorch，这就是预期。

Use TFAutoModel instead =)
Issue Answer Link：https://github.com/huggingface/transformers/issues/4172#issuecomment-625897011
## 2. Compatible with more recent PyTorch versions 更新Torch或transformers
@JTWang2000 Recent versions of transformers are compatible with more recent PyTorch versions, see the README.

@kennylajara could you try upgrading transformers to a more recent version to see if it fixes your issue? (Wav2Vec2 has been improved since v4.3.0) - if not, do you mind linking me to a reproducible code example (with pip installations)/colab notebook or something similar that reproduces your issue?

---

**Try to use Torch 1.9.0 目前尝试使用Toch 1.9.0 可以解决**

**Comment by shm007g** [comment]
```
$ pip install ltp==4.1.4.post1 --upgrade
Successfully installed huggingface-hub-0.0.17 ltp-4.1.4.post1 tokenizers-0.10.3 transformers-4.10.2
$ python -c 'from ltp import LTP'

```

退回到这个版本，出现问题就是在我升级之后。
